// src/components/ATable/Header.vue
<template>
  <div :class="['py-3 flex justify-between items-center text-white border-[#272c39]', {'mb-3 border-b': !props.noSpace}]">
    <span v-for="item in props.options" :key="item" class="text-xs font-semibold">
      {{ item }}
    </span>
  </div>
</template>

<script setup>
const props = defineProps({
  options: {
    type: Array,
    required: true
  },
  noSpace: {
    type: Boolean,
    required: false
  }
})
</script>

// packages/dex/components/Header.tsx
import NetworkSelector from './Wallet/NetworkSelector';
import ConnectWallet from './Wallet/ConnectWallet';

export default function Header() {
  return (
    <div className="py-8">
      <div className="container">
        <div className="flex justify-between items-center">
          <h1 className="font-bold text-xl text-white">Liquid</h1>
          <div className="w-full flex justify-end items-center space-x-3">
            <NetworkSelector />
            <ConnectWallet />
          </div>
        </div>
      </div>
    </div>
  );
}
